apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::446089397912:role/eksctl-flamingo-apparatus-1979-no-NodeInstanceRole-5JVRBEUV23W2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::446089397912:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-24T01:23:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1343"
  uid: 5198211e-750c-4b94-b43f-009c8996706d
